# Generated by Django 5.1.5 on 2025-02-22 19:20

import django.core.validators
import django.db.models.deletion
import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='store/images/default.jpg', upload_to='store/images')),
                ('mobile_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), store.validators.validate_mobile_number])),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.address')),
            ],
        ),
    ]
