# Generated by Django 5.1.5 on 2025-02-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_created_at_store_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
