# Generated by Django 5.1.5 on 2025-02-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_store_name_category_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name_plural': 'Categories'},
        ),
    ]
