# Generated by Django 5.1.5 on 2025-02-24 14:03

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_store_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='store/product/images/default.jpg', upload_to='store/product/images', validators=[store.validators.validate_file_size]),
        ),
    ]
