# Generated by Django 5.1.5 on 2025-02-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
