# Generated by Django 5.1.5 on 2025-03-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_store_is_live'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_store_name',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='unique_store_category'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='unique_store_product'),
        ),
    ]
