# Generated by Django 5.1.5 on 2025-03-03 01:20

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_is_available'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_store_category',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_store_product',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store.address'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('store'), name='unique_store_category_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('store'), name='unique_store_product_case_insensitive'),
        ),
    ]
