# Generated by Django 5.1.5 on 2025-03-03 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.PROTECT, to='store.store'),
            preserve_default=False,
        ),
    ]
