# Generated by Django 5.1.5 on 2025-03-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_order_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('preparing_order', 'Preparing Order'), ('out_for_delivery', 'Out For Delivery'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
