# Generated by Django 5.1.5 on 2025-03-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Preparing Order', 'Preparing Order'), ('Out For Delivery', 'Out For Delivery'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='New', max_length=20),
        ),
    ]
