# Generated by Django 5.1.5 on 2025-03-08 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='store.order'),
        ),
    ]
