# Generated by Django 5.1.5 on 2025-03-08 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_feedback_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='order',
            field=models.ForeignKey(limit_choices_to={'status': 'Completed'}, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='store.order'),
        ),
    ]
