# Generated by Django 5.1.5 on 2025-03-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_feedback_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pick_up_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Pick Up', 'Pick Up')], default='Delivery', max_length=20),
        ),
    ]
