# Generated by Django 5.1.5 on 2025-03-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_order_pick_up_datetime_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Preparing Order', 'Preparing Order'), ('Out For Delivery', 'Out For Delivery'), ('Ready For Pick Up', 'Ready For Pick Up'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='New', max_length=20),
        ),
    ]
