# Generated by Django 5.1.5 on 2025-03-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Being Prepared', 'Being Prepared'), ('Out For Delivery', 'Out For Delivery'), ('Ready For Pick Up', 'Ready For Pick Up'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='New', max_length=20),
        ),
    ]
