# Generated by Django 5.1.5 on 2025-03-03 04:54

import core.models
import core.validators
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='09123456789', max_length=11, validators=[django.core.validators.MinLengthValidator(11), core.models.validate_mobile_number]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(default='+'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 1, 1), validators=[core.validators.validate_age]),
            preserve_default=False,
        ),
    ]
